spring:
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    driver-class-name: org.h2.Driver
    password: 
#    url: jdbc:oracle:thin:@localhost:1521:orcl
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        format_sql: true
    show-sql: true